version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app
    ports:
      - 8000:8000
    env_file:
      - .env/.env.dev
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - dev_car_park_mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'car_db'
      MYSQL_USER: 'car_manager'
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  dev_car_park_mysql_data:


#  redis:
#    image: redis:alpine
#    expose:
#      - 6379
#  celery:
#    restart: always
#    build:
#      context: ./
#      dockerfile: Dockerfile.dev
#    command: celery -A car_park worker -l info
#    env_file:
#      - .env/.env.dev
#    volumes:
#      - dev_web_data:/app/
#    environment:
#      - DB_HOST=db
#      - DB_NAME=car_db
#      - DB_USER=car_manager
#      - DB_PASS=Oaisdi123jaj213
#    depends_on:
#      - db
#      - redis
#      - web
#  telebot:
#    restart: always
#    build:
#      context: ./
#      dockerfile: Dockerfile.dev
#    command: bash -c "cd car_bot/BOT && python telbot.py"
#    env_file:
#      - .env/.env.dev
#    volumes:
#      - dev_web_data:/app/
#    depends_on:
#      - db
#      - web
