version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .web_data:/car_park
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - car_park_mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'car_db'
      MYSQL_USER: 'car_manager'
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'

#  redis:
#    image: redis:alpine
#  celery:
#    restart: always
#    build:
#      context: ./
#    command: celery -A car_park worker -l info
#    volumes:
#      - .:/car_park
#    environment:
#      - DB_HOST=db
#      - DB_NAME=car_db
#      - DB_USER=car_manager
#      - DB_PASS=Oaisdi123jaj213
#    depends_on:
#      - car_db
#      - redis
#      - django


volumes:
  car_park_mysql_data: