FROM python:3.8

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH=$PATH:/app
ENV PYTHONPATH /app

RUN apt-get update && \
    apt-get -y install \
    default-libmysqlclient-dev \
    python3-dev \
    netcat


RUN pip install --upgrade pip
COPY ./req.txt .
RUN pip install -r req.txt

COPY . .

RUN chmod +x entrypoint.prod.sh

ENTRYPOINT ["entrypoint.prod.sh"]
