version: '3.7'
services:
  car_db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'car_db'
      MYSQL_USER: 'car_manager'
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    volumes:
#      - ./db_django:/var/lib/mysql
      - mysql-data:/var/lib/mysql

  django:
     container_name: car_park
     build:
       context: ./
       dockerfile: Dockerfile
     command:
#       ./wait-for-it.sh car_db:3306 &&
       bash -c "python manage.py wait_for_db
       && python manage.py migrate
       && python manage.py runserver 0.0.0.0:8000
       "
#       && python car_bot/BOT/telebot.py
#       "
#     command: pwd
     volumes:
       - .:/usr/src/car_park
     ports:
       - 8000:8000
     depends_on:
#       - redis
       - car_db

  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A car_park worker -l info
    volumes:
      - .:/usr/src/car_park
    environment:
      - DB_HOST=car_db
      - DB_NAME=car_db
      - DB_USER=mysql
      - DB_PASS=123456
    depends_on:
      - car_db
      - redis
      - django
  telebot:
    restart: always
    build:
      context: .
    command: bash -c "cd car_bot/BOT && python telbot.py"
    volumes:
      - .:/usr/src/car_park/
    depends_on:
      - car_db
      - django
volumes:
  mysql-data:
