version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: new_Dockerfile.prod
    command: gunicorn car_park.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .web_data:/car_park
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - car_park_mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  car_park_mysql_data:
