version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn car_park.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - web_data:/home/app/web/
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env/.env.prod
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - car_park_mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env/.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web


  redis:
    image: redis:alpine
    expose:
      - 6379
  celery:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: celery -A car_park worker -l info
    env_file:
      - .env/.env.prod
    volumes:
      - web_data:/home/app/web/
    environment:
      - DB_HOST=db
      - DB_NAME=car_db
      - DB_USER=car_manager
      - DB_PASS=Oaisdi123jaj213
    depends_on:
      - db
      - redis
      - web

volumes:
  car_park_mysql_data:
  static_volume:
  media_volume:
  web_data: