# Generated by Django 4.0.3 on 2022-05-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_bot', '0002_alter_notifications_options_notifications_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='creator',
        ),
    ]
