# Generated by Django 4.0.3 on 2022-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bot', '0003_remove_notifications_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='owner_pk',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
