# Generated by Django 4.0.3 on 2022-03-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='driver',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user_ptr',
        ),
    ]
