# Generated by Django 4.0.3 on 2022-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default='0', verbose_name='Описание'),
        ),
    ]
