# Generated by Django 4.0.3 on 2022-05-22 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_application_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cabinet.car', verbose_name='Машина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_apps', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
