# Generated by Django 4.0.3 on 2022-04-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_myuser_options_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
