# Generated by Django 4.0.3 on 2022-03-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_remove_autodoc_file_remove_driverdoc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='номер телефона'),
        ),
    ]
