# Generated by Django 4.0.3 on 2022-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_application_car_alter_application_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmyuser',
            name='activation_code',
            field=models.CharField(blank=True, default='111111', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, default='111111', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmyuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
