# Generated by Django 4.0.3 on 2022-03-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_driver_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfAppl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='время создания')),
                ('time_to_execute', models.PositiveIntegerField(default=7, verbose_name='время на выполнение')),
                ('end_date', models.DateField(verbose_name='дата окончани')),
                ('onwer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.driver')),
                ('type_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.typeofappl')),
            ],
        ),
    ]
