# Generated by Django 4.0.3 on 2022-04-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('O', 'Ожидает рассмотрения'), ('R', 'Рассмотрена'), ('V', 'Выполнена'), ('P', 'Просрочена')], default='o', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='application',
            name='urgency',
            field=models.CharField(choices=[('N', 'Не срочно'), ('U', 'Срочно'), ('V', 'Очень срочно')], default='N', max_length=1, verbose_name='Cрочность'),
        ),
    ]
