# Generated by Django 4.0.3 on 2022-04-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_application_status_application_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='urgency',
            field=models.CharField(choices=[('N', 'Не срочно'), ('U', 'Срочно'), ('S', 'Очень срочно')], default='N', max_length=1, verbose_name='Cрочность'),
        ),
        migrations.AlterField(
            model_name='userdoc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
