# Generated by Django 4.0.3 on 2022-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_historicalmyuser_chat_id_myuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmyuser',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('m', 'manager'), ('d', 'driver'), ('e', 'engineer')], default='d', max_length=1, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('a', 'admin'), ('m', 'manager'), ('d', 'driver'), ('e', 'engineer')], default='d', max_length=1, verbose_name='Роль'),
        ),
    ]
