# Generated by Django 4.0.3 on 2022-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_typeofappl_alter_user_image_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='typeofappl',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.AlterField(
            model_name='application',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
    ]
