# Generated by Django 4.0.3 on 2022-06-02 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_historicalmyuser_role_alter_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_repair_apps', to=settings.AUTH_USER_MODEL, verbose_name='Механик'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='engineer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Механик'),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_apps', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
