# Generated by Django 4.0.3 on 2022-04-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_application_urgency_alter_userdoc_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodoc',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_docs', to='cabinet.car'),
        ),
    ]
