# Generated by Django 4.0.3 on 2022-04-20 04:55

import cabinet.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_alter_autodoc_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=cabinet.models.Car.upload_image, verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.typeofappl', verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Неправильно совсем!', 'unique': 'Пользователь с таким email уже существует.'}, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
