# Generated by Django 4.0.3 on 2022-03-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_rename_onwer_application_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cabinet.car'),
            preserve_default=False,
        ),
    ]
