# Generated by Django 4.0.3 on 2022-03-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_application_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность заявки'),
        ),
    ]
