# Generated by Django 4.0.3 on 2022-04-25 13:20

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_alter_autodoc_created_at_alter_userdoc_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('O', 'Ожидает рассмотрения'), ('R', 'Рассмотрена'), ('V', 'Выполнена'), ('P', 'Просрочена')], default='O', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cabinet.models.MyUser.path_to_upload_image, verbose_name='Аватарка'),
        ),
    ]
