# Generated by Django 4.0.3 on 2022-06-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Марка'),
        ),
    ]
