# Generated by Django 4.0.3 on 2022-04-25 13:21

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_alter_application_status_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cabinet.models.Car.upload_image, verbose_name='фотография'),
        ),
    ]
