# Generated by Django 4.0.3 on 2022-06-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_alter_carbrand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmyuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmyuser',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ID телеграмм чата'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ID телеграмм чата'),
        ),
    ]
