# Generated by Django 4.0.3 on 2022-03-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_alter_application_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cabinet.car'),
        ),
    ]
