# Generated by Django 4.0.3 on 2022-07-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_alter_historicalmyuser_activation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofappl',
            name='car_is',
        ),
    ]
