# Generated by Django 4.0.3 on 2022-03-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_alter_application_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofappl',
            name='car_is',
            field=models.BooleanField(default=True, verbose_name='Машина или Сотрудник'),
        ),
    ]
