# Generated by Django 4.0.3 on 2022-04-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_typeofappl_car_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcard',
            name='onwer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_cards', to='cabinet.driver'),
        ),
    ]
