# Generated by Django 4.0.3 on 2022-07-08 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_remove_typeofappl_car_is'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmyuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Номер телефона состоит из 11 цифр')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Номер телефона состоит из 11 цифр')], verbose_name='Номер телефона'),
        ),
    ]
