# Generated by Django 4.0.3 on 2022-04-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_alter_fuelcard_onwer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_inspection',
            field=models.DateField(blank=True, null=True, verbose_name='последний осмотр'),
        ),
    ]
