# Generated by Django 4.0.3 on 2022-05-02 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_whitelistemail_remove_myuser_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='manager_descr',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('O', 'Ожидает рассмотрения'), ('R', 'Рассмотрена'), ('V', 'Выполнена'), ('P', 'Просрочена'), ('T', 'Отклонено')], default='O', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
