# Generated by Django 4.0.3 on 2022-04-08 07:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_alter_car_brand_alter_car_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autodoc',
            old_name='expiration_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='driverdoc',
            old_name='expiration_date',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='autodoc',
            name='date_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата выдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverdoc',
            name='date_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата выдачи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='cars', to='cabinet.carbrand', verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='region_code',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200, message='Укажите меньше 200!')], verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Введите номер правильно!', regex='\\w{1}\\d{3}\\w{2}')], verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименования документа'),
        ),
    ]
