# Generated by Django 4.0.3 on 2022-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_rename_expiration_date_autodoc_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodoc',
            name='date_start',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='driverdoc',
            name='date_start',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
    ]
