# Generated by Django 4.0.3 on 2022-05-03 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_autodoc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcard',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
