# Generated by Django 4.0.3 on 2022-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_alter_fuelcard_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='номер телефона'),
        ),
    ]
