# Generated by Django 4.0.3 on 2022-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_alter_autodoc_date_start_alter_driverdoc_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='type',
            field=models.CharField(choices=[('m', 'Человек'), ('c', 'Машина')], default='c', max_length=1),
        ),
    ]
