# Generated by Django 4.0.3 on 2022-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0019_alter_doctype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='type',
            field=models.CharField(choices=[('m', 'Человек'), ('a', 'Машина')], default='a', max_length=1),
        ),
    ]
