# Generated by Django 4.0.3 on 2022-05-05 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0019_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='cars', to='cabinet.carbrand', verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='region_code',
            field=models.PositiveSmallIntegerField(default=123, validators=[django.core.validators.MaxValueValidator(200, message='Укажите меньше 200!')], verbose_name='Код региона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите номер правильно!', regex='\x08\\w{1}\\d{3}\\w{2}\x08')], verbose_name='Регистрационный номер'),
        ),
    ]
