# Generated by Django 4.0.3 on 2022-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0020_alter_doctype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcard',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='номер'),
        ),
    ]
