# Generated by Django 4.0.3 on 2022-05-06 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0020_alter_car_brand_alter_car_region_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Введите номер правильно!', regex='[a-zA-Z][0-9]{3}[a-zA-Z]{2}')], verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_card', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='typeofappl',
            name='car_is',
            field=models.BooleanField(default=True, verbose_name='Машина?'),
        ),
    ]
