# Generated by Django 4.0.3 on 2022-04-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0021_alter_fuelcard_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='остаток'),
        ),
    ]
