# Generated by Django 4.0.3 on 2022-04-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0022_fuelcard_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelcard',
            old_name='onwer',
            new_name='owner',
        ),
    ]
