# Generated by Django 4.0.3 on 2022-05-15 10:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0023_alter_application_car_alter_application_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFuelCard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(blank=True, verbose_name='Лимит')),
                ('number', models.CharField(blank=True, db_index=True, max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Номер')),
                ('balance', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Остаток')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'historical Топливная карта',
                'verbose_name_plural': 'historical Топливные карты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
