# Generated by Django 4.0.3 on 2022-04-09 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0023_rename_onwer_fuelcard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='has_owner',
            field=models.BooleanField(default=False, verbose_name='Есть владелец?'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='номер'),
        ),
    ]
